default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  port: 5432

development:
  <<: *default
  database: iwa_test_app_development

test:
  <<: *default
  database: iwa_test_app_test

production:
  <<: *default
  database: iwa_test_app_production
  username: iwa_test_app
  password: <%= ENV['IWA_TEST_APP_DATABASE_PASSWORD'] %>
